# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35aeba316a843c779dfc6a5ad86d04ac9cec1f061d6ac190c6bb7b5bf6db4b619525a67e5baaafd54c36e50c094e7c8897021ca9e874d27f61b8bcd1f388986a

test:
  secret_key_base: 2a6183a8de2b0676909c7df90cf95db0f57db12276f14aa6b2333c7004e7cdf0efb8bc92f64691ff44f896748603950205c97e2ad316a75c653bbc03cbfe6588

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
